In [1]:
import torch

In [2]:
t = torch.arange(12).reshape(3, 4)
t

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [10]:
t.stride()

(4, 1)

In [3]:
t.flatten()

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
x = torch.transpose(t, 0, 1)
x

tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])

In [11]:
x.stride()

(1, 4)

In [7]:
x.flatten()

tensor([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

In [12]:
x.data_ptr() == t.data.data_ptr()

True

In [13]:
t.is_contiguous(), x.is_contiguous()

(True, False)

In [8]:
x.view(-1)

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [9]:
x.contiguous().view(-1)

tensor([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

# /结果为浮点数，//为整数

In [1]:
x = 2

In [3]:
type(x/2)

float

In [4]:
type(x//2)

int

# mean函数要保证形状不变

In [ ]:
x.mean((2, 3), keepdim=True)

In [3]:
import import_ipynb

In [5]:
import LeNet as ln

In [6]:
net = ln.LeNet()

In [7]:
ln.epochs

5